# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# REDIS CONFIGURATION
# ===============================
spring.redis.host=localhost
spring.redis.port=6379

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*

# ===============================
# SWAGGER (SpringDoc)
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true